In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
heart_data = pd.read_csv('heart.csv')

In [4]:
heart_data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [5]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
X = heart_data.drop(columns = 'target', axis=1)
Y = heart_data['target']

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,stratify= Y, random_state=2)

In [18]:
#creating a list that imported models
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [20]:
def model_accuracy():
    for model in models:
        model.fit(X_train, Y_train)
        test_data_accuracy = model.predict(X_test)
        accuracy = accuracy_score(Y_test, test_data_accuracy)
        print("Accuracy Score is Of ", model, " = ", accuracy)

In [24]:
model_accuracy()

Accuracy Score is Of  LogisticRegression(max_iter=1000)  =  0.8032786885245902
Accuracy Score is Of  SVC(kernel='linear')  =  0.819672131147541
Accuracy Score is Of  KNeighborsClassifier()  =  0.6229508196721312
Accuracy Score is Of  RandomForestClassifier()  =  0.7704918032786885


In [26]:
from sklearn.model_selection import cross_val_score

In [28]:
# using cross_validation for logistic regression
cv_score_lr = cross_val_score(LogisticRegression(max_iter=1000), X, Y, cv=5)
print(cv_score_lr)
mean_accuracy_lr = sum(cv_score_lr)/len(cv_score_lr)
mean_accuracy_lr = mean_accuracy_lr*100
mean_accuracy_lr = round(mean_accuracy_lr,2)
print(mean_accuracy_lr)

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
82.83


/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [30]:
# using cross_validation for SVM
cv_score_svm = cross_val_score(SVC(kernel='linear'), X, Y, cv=5)
print(cv_score_svm)
mean_accuracy_svm = sum(cv_score_svm)/len(cv_score_svm)
mean_accuracy_svm = mean_accuracy_svm*100
mean_accuracy_svm = round(mean_accuracy_svm,2)
print(mean_accuracy_svm)

[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83


In [36]:
def cross_val_accuracy():
    for model in models:
        cv_score = cross_val_score(model, X, Y, cv=5)
        mean_accuracy = sum(cv_score)/len(cv_score)
        mean_accuracy = mean_accuracy*100
        mean_accuracy = round(mean_accuracy,2)
        print(cv_score)
        print(mean_accuracy)
        print("---------------------------------------------")

In [38]:
cross_val_accuracy()

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
82.83
---------------------------------------------
[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83
---------------------------------------------
[0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
64.39
---------------------------------------------
[0.83606557 0.90163934 0.80327869 0.83333333 0.78333333]
83.15
---------------------------------------------
